name: Build Custom Rules DAT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    # Используем собранный тобой образ
    # Замени YOUR_GITHUB_USERNAME на свой логин
    container: ghcr.io/drdelabill/v2dat-runner:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: image_name
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ env.IMAGE_NAME }}
          
      - name: Fetch upstream and diagnose
        run: |
          API_URL="https://api.github.com/repos/runetfreedom/russia-v2ray-rules-dat/releases/latest"
          GEOSITE_URL=$(curl -s $API_URL | jq -r '.assets[] | select(.name=="geosite.dat") | .browser_download_url')
          GEOIP_URL=$(curl -s $API_URL | jq -r '.assets[] | select(.name=="geoip.dat") | .browser_download_url')

          if [ -z "$GEOSITE_URL" ] || [ -z "$GEOIP_URL" ]; then
            echo "Error: Failed to fetch download URLs."
            exit 1
          fi

          echo "Скачивание файлов..."
          curl -L -s -o geosite_full.dat $GEOSITE_URL
          curl -L -s -o geoip_full.dat $GEOIP_URL

          echo "Распаковка..."
          mkdir -p geosite_unpacked geoip_unpacked
          v2dat unpack geosite -o geosite_unpacked geosite_full.dat
          v2dat unpack geoip -o geoip_unpacked geoip_full.dat

          echo "=== Доступные теги в GEOSITE ==="
          ls -1 geosite_unpacked

          echo "=== Доступные теги в GEOIP ==="
          ls -1 geoip_unpacked

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ./geosite.dat
      #       ./geoip.dat
      #     name: Custom Geo Rules
      #     body: "Automated build."
      #     tag_name: |
      #       latest
      #       ${{ github.sha }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
